apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../base
patches:
- target:
    kind: Deployment
    name: causal-consistency-controller
  patch: |-
    - op: replace
      path: /spec/replicas
      value: 5
    - op: add
      path: /spec/template/spec/affinity
      value:
        podAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchLabels:
                  app: causal-consistency
              topologyKey: kubernetes.io/hostname
    - op: add
      path: /spec/template/spec/containers/0/env/-
      value:
        name: DATACENTER
        value: "earth"
    - op: add
      path: /spec/template/spec/containers/0/env/-
      value:
        name: DEVICE_ID
        valueFrom:
          fieldRef:
            fieldPath: metadata.name
    - op: add
      path: /spec/template/spec/volumes
      value:
      - name: db-config
        configMap:
          name: db-config
    - op: add
      path: /spec/template/spec/containers/0/volumeMounts
      value:
      - name: db-config
        mountPath: "/etc/db-config"
        readOnly: true
- target:
    kind: Deployment
    name: causal-consistency-controller
  patch: |-
    - op: add
      path: /metadata/name
      value: causal-consistency-controller-mars
    - op: replace
      path: /spec/replicas
      value: 5
    - op: add
      path: /spec/template/spec/affinity
      value:
        podAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchLabels:
                  app: causal-consistency
              topologyKey: kubernetes.io/hostname
    - op: add
      path: /spec/template/spec/containers/0/env/-
      value:
        name: DATACENTER
        value: "mars"
    - op: add
      path: /spec/template/spec/containers/0/env/-
      value:
        name: DEVICE_ID
        valueFrom:
          fieldRef:
            fieldPath: metadata.name
    - op: add
      path: /spec/template/spec/volumes
      value:
      - name: db-config
        configMap:
          name: db-config
    - op: add
      path: /spec/template/spec/containers/0/volumeMounts
      value:
      - name: db-config
        mountPath: "/etc/db-config"
        readOnly: true
resources:
- redis-service.yaml
- db-config-cm.yaml