apiVersion: v1
kind: Service
metadata:
  name: causal-consistency-controller
  namespace: default
spec:
  selector:
    app: causal-consistency
  ports:
  - port: 8080
    targetPort: 8080
    name: metrics